routes/web.php
<?php

use App\Events\MessageSent;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SearchController@index')->name("search.index");

// Adding new ad
Route::get('/fetch-subcategories', 'AdController@fetchSubcategories')->name("ad.getSubcategories");
Route::get('/fetch-attributes', 'AdController@fetchAttributes')->name("ad.getAttributes");
Route::get('/select-imgs/{ad}', 'AdController@selectImgs')->name("ad.selectImgs");
Route::post('/store-imgs/{ad}', 'AdController@storeImgs')->name("ad.storeImgs");
Route::get('/show-preview/{ad}', 'AdController@showPreview')->name("ad.showPreview");
// TODO redirect->action would suffice(?)
Route::put('/release/{ad}', 'AdController@releaseAd')->name("ad.release");

// Editing Ad
Route::get('/edit-imgs/{ad}', 'AdController@editImgs')->name("ad.editImgs");
// TODO redirect->action would suffice(?)
Route::put('/update-imgs/{ad}', 'AdController@updateImgs')->name("ad.updateImgs");
Route::resource('/ad', 'AdController');


Route::resource('/user', 'UserController');

Route::get('/search-results', 'SearchController@results')->name("search.getResults");

// IMG Route
Route::get('/fetch-image/{image}', 'AdController@outputImg')->name('ad.outputImg');

Auth::routes();

Route::get('/check-login-status', 'UserController@checkLoginStatus')->name("user.check_login_status");
Route::resource("/user", "UserController");

Route::get('/home', 'HomeController@index')->name('home');


// CHAT
Broadcast::routes();
Route::get('/chat', 'ChatController@index')->name("chat");
Route::get('/users', 'UserController@fetchUsers')->name("chat.fetchUsers");
Route::get('/messages/{user}', 'ChatController@fetchMessages');
Route::post('/messages/{user}', 'ChatController@sendMessage');

app/Models/Ad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Ad extends Model
{
    use HasFactory;

    protected $fillable = ["user_id", "district_id", "condition_id", "color_id", "size_id", "shoe_size_id", "waist_size_id", "category_path", "name", "description", "price", "released", "sold"];

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class, "user_id", "id");
    }

    public function imgs()
    {
        return $this->hasMany(\App\Models\Image::class, "ad_id", "id")->orderBy("order_id", "asc");
    }

    public function img()
    {
        // TODO hasOne oder hasMany? orderBy am Ende, weil ich ja noch die order_id brauche
        return $this->hasOne(\App\Models\Image::class, "ad_id", "id")->orderBy("order_id", "asc");
    }

    public function district()
    {
        return $this->hasOne(\App\Models\District::class, "id", "district_id");
    }

    public function color()
    {
        return $this->hasOne(\App\Models\Color::class, "id", "color_id");
    }

    public function condition()
    {
        return $this->hasOne(\App\Models\ClothingCondition::class, "id", "condition_id");
    }

    public function shoeSize()
    {
        return $this->hasOne(\App\Models\ShoeSize::class, "id", "shoe_size_id");
    }

    public function waistSize()
    {
        return $this->hasOne(\App\Models\WaistSize::class, "id", "waist_size_id");
    }

    public function size()
    {
        return $this->hasOne(\App\Models\Size::class, "id", "size_id");
    }
}

app/Http/Controllers/AdController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ad;
use App\Models\Attribute;
use Illuminate\Support\Str;
use App\Models\Category;
use App\Models\ClothingCondition;
use App\Models\Color;
use App\Models\District;
use App\Models\Image;
use App\Models\ShoeSize;
use App\Models\Size;
use App\Models\WaistSize;
use App\Traits\UploadImage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use ReflectionClass;
use stdClass;

class AdController extends Controller
{
    use UploadImage;

    /** @var string Form input name */
    protected $inputFile;

    /** @var string config filesystem disks->index*/
    protected $diskName = "public_image";

    public function __construct()
    {
        $this->middleware(['auth', 'can:registered',])->only("create");
    }

    /**
     * Show all Topcategories
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        // TODO erstes Bild der Anzeigen holen zum Anzeigen
        $adsPaginated = Ad::with("img")->where("released", 1)->paginate(10);
        $topCategories = Category::whereHas("isTopCategory")
            ->leftJoin('ads as a', function ($join) {
                $join->on('categories.id', 'LIKE', DB::raw('SUBSTRING_INDEX(a.category_path,",",1)'))->where("a.released", 1);
            })
            ->selectRaw("categories.*,COUNT(DISTINCT(a.id)) as cat_count")->groupBy("categories.id")->get();

        return view("ad.index", compact("topCategories", "adsPaginated"));
    }

    /** 
     * Fetch subCategories for given categoryId
     */
    public function fetchSubcategories(Request $request)
    {
        $subCategories = Category::where("parent_id", request()->input("prevCategoryId"))->get();
        return response()->json($subCategories);
    }

    /**
     * Fetch Attributes for bottom_categoryId
     * 
     */
    public function fetchAttributes(Request $request)
    {
        // unset previously assigned validationRules (if user changed categories)
        session()->forget("dynamicValidationRules");

        session()->put("dynamicValidationRules", []);

        $attributeTables = Category::findOrFail($request->categoryId)->attributes;
        $attributesData = [];
        foreach ($attributeTables as $attributeTable) {
            $this->setValidationRules($attributeTable->table_name);
            $attributesData[$attributeTable->table_name] = DB::table($attributeTable->table_name)->get();
        }


        $conditions = ClothingCondition::get();
        foreach ($conditions as $condition) {
            $attributesData["conditions"][] = $condition;
        }

        $headers = ["colors" => "Farbe", "sizes" => "Größe", "shoe_sizes" => "Schuhgröße", "waist_sizes" => "Bundweite", "conditions" => "Zustand"];
        $districts = $this->fetchDistricts();
        return response()->json(["attributes" => $attributesData, "districts" => $districts, "headers" => $headers]);
    }

    /**
     * Dynamically set Validationrules when attributes are being fetched
     */
    public function setValidationRules($tableName)
    {
        $validationRule = substr($tableName, 0, strlen($tableName) - 1) . "_id";
        session()->push("dynamicValidationRules", $validationRule);
    }

    public function fetchDistricts()
    {
        return District::get();
    }

    /**
     * Show the first part of the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $topCategories = Category::whereHas("isTopCategory")->get();
        return view("ad.create_details", compact("topCategories"));
    }

    /**
     * Show the second part of the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function selectImgs($id)
    {
        $ad = AD::where(
            ["user_id" => Auth::id(), "released" => 0]
        )
            ->findOrFail($id);
        return view("ad.create_imgs", compact("ad"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // TODO rename in store ad infos (no images)
    public function store(Request $request)
    {
        //! Always present rules 
        $request->validate([
            "name" => "required|min:3",
            "price" => "required|integer|min:0|max:99999",
            "price-comma" => "required|integer|min:0|max:99",
            "topCategory" => "required",
            "subCategories.*" => "required",
            "condition_id" => "required|exists:\App\Models\ClothingCondition,id",
            "district_id" => "required|exists:\App\Models\District,id",
        ]);

        // check which attributes have been set in session to validate
        $this->validateDynamicValidationRules($request);

        $categoryPath = $this->checkCategoryHierarchy($request->subCategories);

        $sessionAtributes = session("dynamicValidationRules");
        $attributes = [];
        foreach ($sessionAtributes as $sessionAtribute) {
            $attributes[$sessionAtribute] = request($sessionAtribute);
        }
        $price = request("price") . "." . request("price-comma");
        $basicData = ["user_id" => Auth::id(), "category_path" => $categoryPath, "name" => request("name"), "condition_id" => request("condition_id"), "district_id" => request("district_id"), "price" => $price, "description" => request("description")];
        $dataForAd = array_merge($basicData, $attributes);

        $ad = new Ad($dataForAd);
        $ad->save();
        session()->forget("dynamicValidationRules");

        //TODO redirect to route with GET Parameter! ID from created ad! Otherwise images will be uploaded anywhere 
        return redirect()->route("ad.selectImgs", $ad->id);
    }

    public function storeImg($key)
    {
        // assign property to $key from form so trait can access file
        $this->inputFile = $key;
        try {
            $this->storeFile();
            $this->resizeMaxWidth(800, "big_");
            $this->resizeMaxWidth(300, "prev_");
        } catch (\Exception $e) {
            if (config("app.debug")) abort("580", $e->getMessage() . ' In Zeile ' . $e->getLine() . '. In Datei ' . $e->getFile());
            abort("580", "Server Fehler, Datei kann nicht gespeichert werden");
        }
        $imgName = $this->traitOriginalFilename;

        // without nulling, each file would be overwritten and only last img would stay 
        $this->traitOriginalFilename = null;

        $order_id = substr($key, strrpos($key, "_") + 1);
        $img = new Image(["ad_id" => request("ad_id"), "order_id" => $order_id, "name" => $imgName]);
        $img->save();
    }

    // TODO rename eher in store Images
    public function storeImgs(Request $request)
    {
        //TODO ajax error validieren? 
        Ad::where([
            "id" => request("ad_id"), "user_id" =>  Auth::id(), "released" => 0,
        ])->findOrFail(request("ad_id"));

        if (request("image_0")) {
            foreach ($request->all() as $key => $image) {
                if (!Str::contains($key, "image")) continue;
                $this->storeImg($key);
            }
        }

        return response()->json(["successRoute" => route("ad.showPreview", request("ad_id"))]);
    }

    public function updateImgs(Request $request)
    {
        $ad = Ad::with("imgs")->where(["id" => request("ad_id"), "user_id" =>  Auth::id()])->findOrFail(request("ad_id"));

        $imgsToRemove = [];
        foreach ($ad->imgs as $img) {
            $imgsToRemove[$img->name] = $img->name;
        }

        if (request("image_0")) {
            foreach ($request->all() as $key => $image) {
                if (!Str::contains($key, "image")) continue;

                // existing picture which isn't a file object or if user updated Imgs but didn't refresh page ($().data() still contains complete file)
                if (is_string($image) || isset($imgsToRemove[preg_replace('![^a-z0-9\.]!i', "_", $image->getClientOriginalName())])) {
                    $order_id = substr($key, strrpos($key, "_") + 1);

                    $imageName = is_string($image) ? $image : preg_replace('![^a-z0-9\.]!i', "_", $image->getClientOriginalName());

                    Image::where("name", $imageName)->update(["order_id" => $order_id]);
                    unset($imgsToRemove[$imageName]);
                } else {
                    $this->storeImg($key);
                }
            }
        }

        foreach ($imgsToRemove as $imgToRemove) {
            Image::where([
                "ad_id" => $ad->id, "name" => $imgToRemove
            ])->delete();
            $this->dropImages($imgToRemove, ["prev_", "big_"]);
        }

        if ($ad->released == 1) return response()->json(["successRoute" => route("ad.show", $ad->id)]);
        else return response()->json(["successRoute" => route("ad.showPreview", $ad->id)]);
    }

    /**
     * Ask user for releasing ad. Show Preview
     */
    public function showPreview(Request $request, $id)
    {
        $ad = AD::with("imgs")->where(["user_id" => Auth::id(), "released" => 0])->findOrFail($id);
        return view("ad.preview", compact("ad"));
    }

    /**
     * Release ad
     */
    public function releaseAd($id)
    {
        $ad = AD::where(["user_id" => Auth::id(), "id" => $id, "released" => 0])->findOrFail($id);
        $ad->update(["released" => 1]);

        return redirect()->route("ad.index")->with("success", "Deine Anzeige wurde erfolgreich veröffentlicht");
    }

    public function validateDynamicValidationRules(Request $request)
    {
        // "color_id" => "exists:\App\Models\Color,id",
        // "size_id" => "exists:\App\Models\Size,id",
        // "waist_size_id" => "exists:\App\Models\WaistSize,id",
        // "shoe_size_id" => "exists:\App\Models\ShoeSize,id",

        $models = [

resources/views/ad/create_details.blade.php
@extends("layouts.app")

@push("scripts")
<script src="{{asset("js/fetch_subcategories_for_add_ad.js")}}"></script>
<script src="{{asset("js/add_new_ad.js")}}"></script>
@endpush

@push("styles")
<link href="{{ asset('css/create.css') }}" rel="stylesheet">
@endpush

@section("content")
@if(session("success"))
<div class="alert alert-success">{{session("success")}}</div>
@elseif(session("error"))
<div class="alert alert-danger">{{session("error")}}</div>
@endif

<input type="hidden" name="fetchSubCategoriesRoute" value="{{route("ad.getSubcategories")}}"></input>
<input type="hidden" name="fetchAttributesRoute" value="{{route("ad.getAttributes")}}"></input>

<div class="my-5">
   <a href="{{route("ad.index")}}">Zu Allen Inseraten</a>
   <h3>Neues Inserat</h3>
   <div class="new-ad-container">
      <form id="add-new-ad" action="{{route("ad.store")}}" method="post" enctype="multipart/form-data">
         @csrf
         <div class="input-container">
            <div class="ad my-3">
               <div>
                  <label for="name">Titel</label>
                  <input type="text" id="ad-name" name="name" value="{{old("name")}}" autocomplete="off">
               </div>
               @error("name")
               <div class="alert alert-danger">{{$message}}</div>
               @enderror
               <div>
                  <label for="price">Preis</label>
                  <input type="number" id="ad-price" name="price" min="0" max="99999" value="{{old("price") ?? 0}}"
                     autocomplete="off">
                  @error("price")
                  <div class="alert alert-danger">{{$message}}</div>
                  @enderror
                  <span>,</span>
                  <input type="number" id="ad-price-comma" name="price-comma" value="{{old("price-comma") ?? 00}}"
                     autocomplete="off" min="0" max="99">
                  @error("price-comma")
                  <div class="alert alert-danger">{{$message}}</div>
                  @enderror
               </div>
            </div>

            <div class="categories-container">
               <h3>Kategorien</h3>
               <div class="d-flex flex-wrap ">
                  <div class="category">
                     <select id="1" name="topCategory" size="7">
                        @foreach($topCategories as $topCategory)
                        <option value='{{$topCategory->id}}' name='{{$topCategory->name}}'> {{$topCategory->name}}
                        </option>
                        @endforeach
                     </select>
                  </div>
               </div>
            </div>
            @error("topCategory")
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
            @error("subCategories.*")
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
         </div>
         <button id="add-ad-button" type="submit">Speichern und Weiter</button>
      </form>

   </div>
</div>
<script>
   const price = document.querySelector("#ad-price");
   price.onkeyup = function(e){
      if(this.value.length >=5){
         this.value = this.value.substring(0,5);
      }
   }

   const priceComma =document.querySelector("#ad-price-comma");
   priceComma.onkeyup = function(e){
      if(this.value.length >=2){
         this.value = this.value.substring(0,2);
      }
   }
   
</script>
@endsection

resources/views/ad/create_imgs.blade.php
@extends("layouts.app")

@section("content")
@if(session("success"))
<div class="alert alert-success">{{session("success")}}</div>
@elseif(session("error"))
<div class="alert alert-danger">{{session("error")}}</div>
@endif


<div class="my-5">
   <div>
      <a class="btn btn-primary" href="{{route("ad.index")}}">Zu Allen Inseraten</a>
      <a class="btn btn-warning" href="{{route("ad.edit",$ad->id)}}">Kategorien überarbeiten</a>
   </div>
   <h3>Bilder hinzufügen</h3>
   <p>Das oberste Bild ist dein Anzeigebild</p>
   <p>Ziehe die Bilder mit der Maus, wenn du die Reihenfolge ändern möchtest</p>
   <div class="img-container">
      <form id="add-new-ad" action="{{route("ad.storeImgs",$ad->id)}}" method="post" enctype="multipart/form-data">
         @csrf
         <input type="file" class="form-control-file d-none" id="upload-img" multiple>
         <button class="btn btn-primary submit">Speichern und Weiter</button>
      </form>
   </div>
   <button id="myButton" type="button" class="btn btn-success">+ Bilder hochladen</button>
   <ul id="images">
   </ul>
</div>

{{-- Animation --}}
<div class="overlay">
   <div class="lds-dual-ring"></div>
</div>

{{-- TODO ID anders einlesen, sprich umbauen zu normaler Route --}}
<input type="hidden" name="ad_id" value={{$ad->id}}>


{{-- <button id="mySubmitButton" type="button" style="border-radius: 5px; background-color: #fff; color: green;">Send
   Files</button> --}}

<div id="myFiles"></div>

<script>
   // TODO SCRIPT AUSLAGERN
   $(function(){
      // Reorder IDs in DOM
      function reorderIds(){
            $("#images li").each((idx,el) => $(el).attr("id",idx));
         }

      function dragImgs(){

         // remove all previously attached eventlisteners
         $("#images li").off();

         $("#images li").attr("draggable",true);

         reorderIds();

         var dragged = null;

         $("#images li").on("dragstart",function(e){
               // get native Event and Element
               e.originalEvent.dataTransfer.setDragImage($(e.target)[0], 150, 150);
               dragged = this;

               for(const li of $("#images li")){
                  if(li != this) $(li).addClass("hint")
               }
            })

         $("#images li").on("dragenter", function (ev) {
            if (this != dragged) { 
               this.classList.add("active"); 
            }
         });

         $("#images li").on("dragleave", function (e) {
            this.classList.remove("active");
         });

         // remove all added classes when dragging stops
         $("#images li").on("dragend", function () {
            for (const li of $("#images li")) {
               $(li).removeClass("hint");
               $(li).removeClass("active");
            }
         });

         // Allow custom dropping (fired every time an element gets dragged over a valid drop target)
         $("#images li").on("dragover", function(e){
            e.preventDefault();
         });

         $("#images li").on("drop",function dropHandler(e){
            e.preventDefault();
            // Fetch all images, because order changes after each drop
            var items = $("#images li");
            // If element that is getting dropped upon isn't the dragged one, continue
            if (this != dragged) {
               let oldPos = 0, droppedPos = 0;
               for (let it=0; it<items.length; it++) {
                  // oldPos = position in DOM before dragging (ex: first element (index=0))
                  if (dragged == items[it]) oldPos = it; 
                  // droppedPos = position of element that is dropped upon (ex: second element (index=1))
                  if (this == items[it]) droppedPos = it; 
               }
               // oldPos = 0, droppedPos = 1, this = li at droppedPos(index = 1), this.nextSibling = li(index = 2). 
               // firstLi gets inserted in front of the nextSibling of secondLi (= thirdLi)
               if (oldPos < droppedPos) this.parentNode.insertBefore(dragged, this.nextSibling);
               // dragger = 3, Ziehen auf 1, this = 1, also füge 3 vor 1 ein
               else this.parentNode.insertBefore(dragged, this);
            }
            // set img ids for database show order
            reorderIds();
         });
      };

      
      function readFile(file) {
         return new Promise((resolve, reject) => {
            const reader = new FileReader();

            reader.onload = res => {
            resolve(res.target.result);
            };
            reader.onerror = err => reject(err);

            reader.readAsDataURL(file);
         });
      }

      $("#myButton").on("click",() => $('#upload-img').trigger("click"));

      $("#upload-img").change(async() => {
         const files = document.querySelector('[type=file]').files;
         for(const file of files){
            $(".overlay").addClass("d-flex");
            const content = await readFile(file);
            var img = document.createElement("img");

            // wird gefeuert, sobald ich img.src setze (weiter unten)
            img.onload = function(){
               var canvas = document.createElement("canvas");
               var ctx = canvas.getContext("2d");
               ctx.drawImage(img, 0, 0);

               // Lege Größe fest TODO andere Bildschirme unterstützen
               const MAX_WIDTH = 300;
               const HEIGHT = 150;

               // Bildgrößen
               var width = img.width;
               var height = img.height;
               
               // Vergleiche Bildgrößen und passe sie, wenn nötig an MAX_WIDTH / HEIGHT an
               if (width > height) {
                  if (width > MAX_WIDTH) {
                     height *= MAX_WIDTH / width;
                     width = MAX_WIDTH;
                  }
               } else {
                  if (height > HEIGHT) {
                     width *= HEIGHT / height;
                     height = HEIGHT;
                  }
               }
               // Canasgrößen
               canvas.width = width;
               canvas.height = HEIGHT;
               var ctx = canvas.getContext("2d");
               
               // Zeichen Bild mit den runtergesetzten Dimensionen
               ctx.drawImage(img, 0, 0, width, height);
               
               // erstellt eine URL aus der übergebenen Datei, die ich dann bei der img.src einsetzen kann
               dataurl = canvas.toDataURL(file.type);
               
               const previewImages = document.querySelector("#images")
               const li = document.createElement("li");
               li.classList.add("d-flex");
               const previewImg = $(`<img class='file ml-auto' src=${dataurl}>`).data('fileData',file)
               const removeBtn = $("<button></button>").addClass("btn btn-danger ml-auto align-self-start").text("X");
               $(removeBtn).on("click",function(e){
                  e.preventDefault();
                  $(this).closest("li").remove();
                  reorderIds();
               })

               $(li).append(previewImg);
               $(li).append(removeBtn);
               $(previewImages).append($(li));
               dragImgs();
            }
            // durch das setzen der src feuert img.onload
            img.src = content;
         }   
         console.log("Preview Upload finished,cancel animation");
         $(".overlay").removeClass("d-flex");
      })
   })


   // Submit Form
   $('form .btn.submit').on("click",function(e) {
      $(".overlay").addClass("d-flex");
      e.preventDefault();
      const formData = new FormData();
      
      $("#images li img").each((idx,el)=>{
         console.log("submitted. El.data",$(el).data("fileData"));
         // Damit ich die Bilder im Trait ansprechen kann, brauchen sie alle eigene keys und kein Array
         formData.append(`image_${idx}`, $(el).data("fileData"));
      })

      // zum Auslesen des Formdataobjekts, ob es klappt 
      for(const keyValue of formData){
         console.log("Form key value pair",keyValue);
         const indexforDb = keyValue[0].substring(keyValue[0].lastIndexOf('_') + 1);
      }

      // return;
      
      // formData.set("images",$("#images p:first").data("fileData"))
      formData.append("ad_id",$("[name=ad_id]").val());
      console.log('Sending...');
      
      $.ajax({
         url: $("form#add-new-ad").attr("action"),
         headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
         },
         data: formData,
         type: 'POST',
         contentType:"application/x-www-form-urlencoded",
         success: function(data) { 
            console.log('SUCCESS !!!');
            console.log("DATA",data); 
            window.location.href = data.successRoute;
            // TODO Redirect to Next Step
            },
         error: function(data) { 
            console.log('ERROR !!!'); 
            // TODO Redirect 404
         },
         cache: false,
         processData: false,
         contentType: false
      });
   });




</script>


<style>
   /* TODO STYLE AUSLAGERN */
   .holder {
      height: 300px;
      width: 300px;
      border: 2px solid black;
   }

   /* Da beim drawImg alles in Proportionen passiert, muss ich nichts festlegen */
   img {
      /* max-width: 300px;
      max-height: 150px;
      min-width: 300px;
      height: 150px; */
      /* object-fit: contain; */
   }

   input[type="file"] {
      margin-top: 5px;
   }

   .heading {
      font-family: Montserrat;
      font-size: 45px;
      color: green;
   }

   .hint {
      background: yellow;
   }

   .active {
      background: green;
   }

   ul#images {
      list-style: none;
   }

   ul#images li {
      text-align: center;
      border: 1px solid black;
      padding: .5rem;
   }

   /* Necessary to prevent the removal of classes when dragging over img/parent  */
   img {
      pointer-events: none;
   }

   /* Overlay für Animation */

   /* TODO STYLE AUSLAGERN */

   .overlay {
      min-height: 100vh;
      background: rgba(0, 0, 0, .3);
      position: fixed;
      display: none;
      justify-content: center;
      align-items: center;
      top: 0;
      left: 0;
      width: 100%;
   }

   /* Animation */

   .lds-dual-ring {
      display: inline-block;
      width: 80px;
      height: 80px;
   }

   .lds-dual-ring:after {
      content: " ";
      display: block;
      width: 64px;
      height: 64px;
      margin: 8px;
      border-radius: 50%;
      border: 6px solid #fff;
      border-color: #fff transparent #fff transparent;
      animation: lds-dual-ring 1.2s linear infinite;
   }

   @keyframes lds-dual-ring {
      0% {
         transform: rotate(0deg);
      }

      100% {
         transform: rotate(360deg);
      }
   }
</style>
@endsection

resources/views/ad/index.blade.php
@extends("layouts.app")


@push("scripts")
<script src="{{asset("js/fetch_products_from_top_category.js")}}"></script>
@endpush

@section("content")

@if(session("success"))
<div class="alert alert-success"> {{session("success")}}</div>
@endif
<div>
   <a class="add-new-ad" href="{{route("ad.create")}}">Neues Inserat aufgeben</a>
</div>
<ul>
   <li> {{$topCategories[0]->parent->name}}
      <ul>
         @foreach($topCategories as $category)
         <li>
            <a
               href="{{route("search.getResults")}}?category_path={{$category->id}},&currCatId={{$category->id}}&currLevel=1&keyword=">{{$category->name}}
               ({{$category->cat_count}})</a>
         </li>
         @endforeach
      </ul>
   </li>
</ul>
<div class="d-flex y-5">
   <div class="align-self-center mr-2">
      <form id="search" action={{route("search.getResults")}} method="GET" autocomplete="off">
         <h4 class="text-center">Suche</h4>
         <div class="input-container">
            <input type="text" name="keyword" value='{{$_GET["keyword"] ?? ""}}'>
         </div>
         @foreach($_GET as $key => $value)
         @if ($key == "keyword" || $key == "page") @continue @endif
         <input type="hidden" name={{$key}} value={{$value}}>
         @endforeach
         <div class="button-container text-center"><button type="submit">Suchen</button></div>
      </form>
      <div class="results"></div>
   </div>
   <div class="align-self-center">
      <form action={{route("search.getResults")}} method="GET">
         @foreach($_GET as $key => $value)
         @if ($key == "keyword" || $key == "page") @continue @endif
         <input type="hidden" name={{$key}} value={{$value}}>
         @endforeach
         <button type="submit">Suchbegriff entfernen</button>
      </form>
   </div>
</div>


<div class="my-5">
   @if (!count($adsPaginated))
   @if (!isset($_GET["keyword"]) || $_GET["keyword"] == false)
   <h3> Es sind noch keine Einträge vorhanden </h3>
   @elseif(isset($_GET["keyword"]))
   <h3>Keine Einträge für '{{$_GET["keyword"]}}'</h3>
   @endif
   @else
   <h3 class="text-center">{{$adsPaginated->total()}} @if ($adsPaginated->total() == 1) Eintrag @else Einträge
      @endif
      @if(isset($_GET["keyword"]) && $_GET["keyword"])
      für '{{$_GET["keyword"]}}'@endif
   </h3>
   @endif

   {{$adsPaginated->links('pagination::bootstrap-4')}}
   @foreach($adsPaginated as $ad)
   <div style="border:1px solid; text-align:center">
      <a href="{{route("ad.show",$ad->id)}}">
         <img src=@if($ad->img) {{route("ad.outputImg","prev_".$ad->img->name )}} @else
         {{asset("img/photo-placeholder-icon-3.jpg")}} @endif
         width="150"
         height="100" style="object-fit:contain" alt="">
         <p>{{$ad->name}}</p>
      </a>
   </div>
   @endforeach
</div>


@endsection