routes/web.php
<?php

use App\Events\MessageSent;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SearchController@index')->name("search.index");

// Adding new ad
Route::get('/fetch-subcategories', 'AdController@fetchSubcategories')->name("ad.getSubcategories");
Route::get('/fetch-attributes', 'AdController@fetchAttributes')->name("ad.getAttributes");
Route::get('/select-imgs/{ad}', 'AdController@selectImgs')->name("ad.selectImgs");
Route::post('/store-imgs/{ad}', 'AdController@storeImgs')->name("ad.storeImgs");
Route::get('/show-preview/{ad}', 'AdController@showPreview')->name("ad.showPreview");
// TODO redirect->action would suffice(?)
Route::put('/release/{ad}', 'AdController@releaseAd')->name("ad.release");

// Editing Ad
Route::get('/edit-imgs/{ad}', 'AdController@editImgs')->name("ad.editImgs");
// TODO redirect->action would suffice(?)
Route::put('/update-imgs/{ad}', 'AdController@updateImgs')->name("ad.updateImgs");
Route::resource('/ad', 'AdController');


Route::resource('/user', 'UserController');

Route::get('/search-results', 'SearchController@results')->name("search.getResults");

// IMG Route
Route::get('/fetch-image/{image}', 'AdController@outputImg')->name('ad.outputImg');

Auth::routes();

Route::get('/check-login-status', 'UserController@checkLoginStatus')->name("user.check_login_status");
Route::resource("/user", "UserController");

Route::get('/home', 'HomeController@index')->name('home');


// CHAT
Broadcast::routes();
Route::get('/chat', 'ChatController@index')->name("chat");
Route::get('/users', 'UserController@fetchUsers')->name("chat.fetchUsers");
Route::get('/messages/{user}', 'ChatController@fetchMessages');
Route::post('/messages/{user}', 'ChatController@sendMessage');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/check_if_user_is_logged_in.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @stack('styles')

    {{-- Style auslagern --}}
    <style>
        .chat {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        .chat li {
            margin-bottom: 10px;
            padding-bottom: 5px;
            border-bottom: 1px dotted #B3A9A9;
        }

        .chat li .chat-body p {
            margin: 0;
            color: #777777;
        }

        .panel-body {
            overflow-y: scroll;
            height: 350px;
        }

        ::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
            background-color: #F5F5F5;
        }

        ::-webkit-scrollbar {
            width: 12px;
            background-color: #F5F5F5;
        }

        ::-webkit-scrollbar-thumb {
            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
            background-color: #555;
        }
    </style>
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @endif

                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('user.index') }}">Deine Anzeigen</a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @yield('content')
        </main>
    </div>
    @stack("scripts")

    <div class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="text-center"></p>
                </div>
                <div class="modal-footer">

                    <a href="{{route("login")}}"><button type="button" class="btn btn-success">Einloggen</button></a>
                    <a href="{{route("register")}}"><button type="button"
                            class="btn btn-primary">Registrieren</button></a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        // window.onload = function(){
        //     let script = document.createElement('script');    
        //     // can load any script, from any domain
        //     script.src = "js/app.js";
        //     document.head.append(script);
        // }
    </script>

</body>

</html>